export const INCREMENT = "INCREMENT";
export const INCREMENT_AMOUNT = "INCREMENT_AMOUNT";
export const DECREMENT = "DECREMENT";

export const INCREMENT_WATCHER = "INCREMENT_WATCHER";
export const INCREMENT_ASYNC_REQUEST = "INCREMENT_ASYNC_REQUEST";
export const INCREMENT_ASYNC_SUCCESS = "INCREMENT_ASYNC_SUCCESS";
export const INCREMENT_ASYNC_FAIL = "INCREMENT_ASYNC_FAIL";
